name: .NET Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test RandomStringGenerator.Tests/RandomStringGenerator.Tests.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish --no-build --verbosity normal
      
    - name: Create Archive
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        directory: 'RandomStringGenerator/bin/Release/net9.0/publish'
        filename: 'RandomStringGenerator.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
          
    - uses: ncipollo/release-action@v1
      with:
        name: Release ${{ github.ref }}
        tag: ${{ github.ref }}
        artifacts: "RandomStringGenerator/bin/Release/net9.0/publish"
