name: .NET Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest

    env:
        program_project: RandomStringGenerator/RandomStringGenerator.csproj
        test_project: RandomStringGenerator.Tests/RandomStringGenerator.Tests.csproj
        zip_file: RandomStringGenerator.zip
        publish_dir: RandomStringGenerator/bin/Release/net9.0/publish

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build
    
    - name: Test
      run: dotnet test ${{ env.test_project }}

    - name: Publish
      run: dotnet publish ${{ env.program_project }} -c Release -o ${{ env.publish_dir }}
      
    - name: Create Archive
      uses: thedoctor0/zip-release@0.7.5
      with:
        directory: ${{ env.publish_dir }}
        filename: ${{ env.zip_file }}
          
    - uses: ncipollo/release-action@v1
      with:
        name: Release ${{ github.ref }}
        tag: ${{ github.ref }}
        artifacts: ${{ env.publish_dir }}
