name: .NET Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: write

env:
    program_project: RandomStringGenerator/RandomStringGenerator.csproj
    test_project: RandomStringGenerator.Tests/RandomStringGenerator.Tests.csproj
    zip_file: RandomStringGenerator.zip
    publish_dir: RandomStringGenerator/bin/Release/net9.0/publish

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Build
      run: dotnet build
    
    - name: Test
      run: dotnet test ${{ env.test_project }}

  Release:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Publish
      run: dotnet publish ${{ env.program_project }} -c Release -o ${{ env.publish_dir }}
      
    - name: Create Archive
      uses: thedoctor0/zip-release@0.7.5
      with:
        directory: ${{ env.publish_dir }}
        filename: ${{ env.zip_file }}
          
    - uses: ncipollo/release-action@v1
      with:
        name: Release ${{ github.run_number }}
        tag: ${{ github.run_id }}
        artifacts: ${{ env.publish_dir }}/${{ env.zip_file }}
        token: ${{ secrets.GITHUB_TOKEN }}
